// PGlite is loaded from our own origin at runtime rather than bundled, because Turbopack
// rewrites its Emscripten glue into something that fails with "m.instantiateWasm is not a
// function" - passing prebuilt WebAssembly.Modules does not avoid it. Its dist is plain
// ESM with relative chunk imports, so the browser can load it unaided from /pglite.
//
// Source maps are skipped; everything else is copied because index.js reaches for sibling
// chunks, the wasm/data pair, and the fs directory. Gitignored and regenerated by
// prebuild/predev rather than committed.
import { cpSync, mkdirSync, rmSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname } from "node:path";

// Resolved from the package entry, not "@electric-sql/pglite/package.json": that subpath
// is not in its exports map, so requiring it throws ERR_PACKAGE_PATH_NOT_EXPORTED.
const require = createRequire(import.meta.url);
const dist = dirname(require.resolve("@electric-sql/pglite"));
const out = "public/pglite";

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(dist, out, {
  recursive: true,
  filter: (src) => !src.endsWith(".map"),
});
console.log(`copied pglite dist to ${out}`);
