// PGlite is served from our origin because Turbopack breaks its Emscripten glue. Its dist is
// plain ESM with relative chunk imports, so the browser loads it unaided - which is why the
// whole dist is copied, not just the wasm. Gitignored; regenerated by prebuild/predev.
import { cpSync, mkdirSync, rmSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname } from "node:path";

// Resolved from the package entry, not "@electric-sql/pglite/package.json": that subpath
// is not in its exports map, so requiring it throws ERR_PACKAGE_PATH_NOT_EXPORTED.
const require = createRequire(import.meta.url);
const dist = dirname(require.resolve("@electric-sql/pglite"));
const out = "public/pglite";

rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
cpSync(dist, out, {
  recursive: true,
  filter: (src) => !src.endsWith(".map"),
});
console.log(`copied pglite dist to ${out}`);
